### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/pyepics-feedstock#1]
@stuartcampbell @licode @jrmlhermitte any interest in being added? (or anyone I missed?)

**Comment by jrmlhermitte** [comment]
yes thanks!

**Comment by jrmlhermitte** [comment]
@danielballan perhaps and maybe @tacaswell

**Comment by jrmlhermitte** [comment]
@mrakitin as well

**Comment by stuartcampbell** [comment]
Happy to help

**Comment by CJ-Wright** [comment]
@mrakitin any interest?

**Comment by mrakitin** [comment]
Sure, with pleasure!

**Comment by danielballan** [comment]
@dchabot has done some work on pyepics packaging. @klauer might also be interested.
