### ISSUE TITLE
Build binaries instead of vendoring them

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/pyepics-feedstock#13]
Currrently this recipe vendors in several .so files that are present in the source tarball.  These have not neccesarily been built with conda-forge compilers and dependencies and may have binary incompatibility.

**Comment by tacaswell** [comment]
We should pull the changes from https://github.com/NSLS-II/lightsource2-recipes/tree/master/recipes-tag/pyepics into conda forge.

We can remove all of the binaries, patch out the non-standard library discovery, and depend on `epics-base` which is now built on all of the platfroms by conda-forge (https://anaconda.org/conda-forge/epics-base)

**Comment by CJ-Wright** [comment]
Sounds great!

**Comment by mrakitin** [comment]
The patch is already in,

**Comment by mrakitin** [comment]
Sorry, closed by mistake.
